name: Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: 8
      - run: echo 'dotnet version ${{ steps.setup-dotnet.outputs.dotnet-version }}
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: 20
      - run: echo 'node version ${{ steps.setup-node.outputs.node-version }}
      - run: dotnet publish